# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('second_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Picu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('street_address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
            ],
        ),
    ]
