# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('admitted_from', models.CharField(max_length=300)),
                ('admission_diagnosis', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Child',
            new_name='Patient',
        ),
        migrations.AlterModelOptions(
            name='picu',
            options={'verbose_name_plural': 'Pediatric ICUS'},
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picu.Patient'),
        ),
    ]
