# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0002_auto_20161118_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharge_diagnosis',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharged_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_deceased',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='hiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_diagnosis',
            field=models.TextField(max_length=1000),
        ),
    ]
