# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0003_auto_20161118_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PositiveCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picu.Culture')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picu.Patient')),
            ],
        ),
    ]
