# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0005_auto_20161119_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_diagnosis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='picu.Diagnosis'),
        ),
        migrations.AddField(
            model_name='admission',
            name='positive_cultures',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='picu.Culture'),
        ),
    ]
