# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0007_auto_20161119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_deceased',
            field=models.DateField(default=None, null=True),
        ),
    ]
