# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0009_auto_20161119_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='admission_diagnosis',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_diagnosis',
            field=models.ManyToManyField(default=None, to='picu.Diagnosis'),
        ),
        migrations.RemoveField(
            model_name='admission',
            name='positive_cultures',
        ),
        migrations.AddField(
            model_name='admission',
            name='positive_cultures',
            field=models.ManyToManyField(default=None, to='picu.Culture'),
        ),
    ]
