# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0011_auto_20161119_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status_on_admission',
            field=models.BooleanField(default=False),
        ),
    ]
