# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0012_patient_status_on_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status_on_admission',
        ),
    ]
