# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0013_remove_patient_status_on_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='base_excess',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharged_to',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='admission',
            name='elective_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='mechanical_ventilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='pupils_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='spb',
            field=models.IntegerField(default=0),
        ),
    ]
