# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:57
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0014_auto_20161121_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('sort_order', models.IntegerField(max_length=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picu.SelectionType')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='fraction_inspired_oxygen',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='admission',
            name='partial_oxygen_pressure',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharge_diagnosis',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharged_to',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
