# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0015_auto_20161122_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='spb',
            new_name='sbp',
        ),
        migrations.AlterField(
            model_name='selectionvalue',
            name='sort_order',
            field=models.IntegerField(),
        ),
    ]
