# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0016_auto_20161122_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='risk_associated_with_diagnosis',
            field=models.CharField(choices=[('1', 'Low Risk'), ('2', 'High Risk'), ('3', 'Very High Risk')], default=None, max_length=1),
        ),
    ]
