# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0018_auto_20161123_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='bypass_cardiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='non_bypass_cardiac',
            field=models.BooleanField(default=False, verbose_name='Non-bypass cardiac'),
        ),
        migrations.AddField(
            model_name='admission',
            name='non_cardiac_procedure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectionvalue',
            name='numeric_value',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='base_excess',
            field=models.FloatField(default=0.0, verbose_name='Absolute value of base excess (mmol/L)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharged_to',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='fraction_inspired_oxygen',
            field=models.FloatField(default=0.0, verbose_name='FiO2 as Decimal'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mechanical_ventilation',
            field=models.BooleanField(default=False, verbose_name='Mechanical ventilation in the first hour?'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='partial_oxygen_pressure',
            field=models.FloatField(default=0.0, verbose_name='PaO2 mmHg'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pupils_fixed',
            field=models.BooleanField(default=False, verbose_name='Pupils Fixed To Light?'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sbp',
            field=models.IntegerField(default=0, verbose_name='SBP at admission (mm Hg)'),
        ),
    ]
