# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0019_auto_20161123_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_deceased',
        ),
        migrations.AlterField(
            model_name='admission',
            name='admitted_from',
            field=models.CharField(max_length=300, verbose_name='Referred From'),
        ),
    ]
