# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0020_auto_20161125_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admission_date',
            new_name='picu_admission_date',
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital_admission_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='anzics_code',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd_10_code',
            field=models.CharField(default='temp2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picu',
            name='unit_number',
            field=models.IntegerField(default='123456'),
            preserve_default=False,
        ),
    ]
