# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picu', '0021_auto_20161213_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiondiagnosis',
            options={'verbose_name_plural': 'Admission Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.RemoveField(
            model_name='positiveculture',
            name='patient',
        ),
        migrations.AddField(
            model_name='picu',
            name='case_number',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picu',
            name='hospital_number',
            field=models.CharField(default=23455567, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positiveculture',
            name='admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picu.Admission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picu',
            name='unit_number',
            field=models.CharField(max_length=200),
        ),
    ]
